-- Generated by Gemini

local M = {}

-- Setup Namespace and Highlight Group
M.ns = vim.api.nvim_create_namespace("QuickMark")
vim.api.nvim_set_hl(0, "QuickMarkLine", { bg = "#3e4452", bold = true, fg = "#abb2bf" })

-- 1. Toggle Highlight on Current Line
function M.toggle()
    local buf = vim.api.nvim_get_current_buf()
    local row = vim.api.nvim_win_get_cursor(0)[1] - 1
    local marks = vim.api.nvim_buf_get_extmarks(buf, M.ns, {row, 0}, {row, -1}, {})

    if #marks > 0 then
        vim.api.nvim_buf_del_extmark(buf, M.ns, marks[1][1])
    else
        vim.api.nvim_buf_set_extmark(buf, M.ns, row, 0, {
            line_hl_group = "QuickMarkLine",
            sign_text = ">>",
            sign_hl_group = "DiagnosticSignInfo",
        })
    end
end

-- 2. Push all Extmarks in current buffer to Quickfix
function M.send_to_qf()
    local buf = vim.api.nvim_get_current_buf()
    local buf_name = vim.api.nvim_buf_get_name(buf)
    local marks = vim.api.nvim_buf_get_extmarks(buf, M.ns, 0, -1, { details = true })
    local qf_list = {}

    for _, mark in ipairs(marks) do
        local row = mark[2] + 1
        local text = vim.api.nvim_buf_get_lines(buf, row - 1, row, false)[1] or ""
        table.insert(qf_list, {
            bufnr = buf,
            filename = buf_name,
            lnum = row,
            col = 1,
            text = "[Mark] " .. vim.trim(text)
        })
    end

    if #qf_list > 0 then
        vim.fn.setqflist(qf_list, 'r')
        vim.cmd("copen")
    else
        print("No marks to list.")
    end
end

-- 3. Clear Everything
function M.clear_all()
    vim.api.nvim_buf_clear_namespace(0, M.ns, 0, -1)
    vim.fn.setqflist({}, 'r')
    print("QuickMarks wiped.")
end

-- 4. Keybindings
vim.keymap.set('n', 'mm', M.toggle, { desc = "Toggle Mark Highlight" })
vim.keymap.set('n', 'ml', M.send_to_qf, { desc = "List Marks in Quickfix" })
vim.keymap.set('n', 'mc', M.clear_all, { desc = "Clear all Marks" })

return M
